import { query, getClient } from './db';
import { logger } from './logger';
import { PoolClient } from 'pg';

const serviceLogger = logger.createChild('recurring-service');

/**
 * Recurring Appointments Service
 * Handles creation, listing, updating, and deletion of recurring appointments
 * Automatically generates appointments based on recurrence schedule
 */

export interface RecurringAppointment {
  id: number;
  shop_id: number;
  customer_id: number;
  barber_id: number | null;
  service_name: string | null;
  recurrence_type: 'weekly' | 'bi-weekly' | 'monthly';
  recurrence_interval: number;
  day_of_week: number | null;
  day_of_month: number | null;
  time_of_day: string;
  start_date: string;
  end_date: string | null;
  is_active: boolean;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface AutoGeneratedAppointment {
  id: number;
  recurring_appointment_id: number;
  appointment_id: number;
  generated_at: string;
}

/**
 * Create a new recurring appointment
 */
export async function createRecurringAppointment(
  data: {
    customerId: number;
    barberId?: number;
    shopId: number;
    serviceName?: string;
    recurrenceType: 'weekly' | 'bi-weekly' | 'monthly';
    dayOfWeek?: number;
    dayOfMonth?: number;
    timeOfDay: string;
    startDate: string;
    endDate?: string;
    notes?: string;
  }
): Promise<RecurringAppointment | null> {
  const client = await getClient();

  try {
    await client.query('BEGIN');

    const result = await client.query(
      `INSERT INTO recurring_appointments (
        shop_id, customer_id, barber_id, service_name, recurrence_type,
        day_of_week, day_of_month, time_of_day, start_date, end_date, notes, is_active
      ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, true)
      RETURNING *`,
      [
        data.shopId,
        data.customerId,
        data.barberId || null,
        data.serviceName || null,
        data.recurrenceType,
        data.dayOfWeek || null,
        data.dayOfMonth || null,
        data.timeOfDay,
        data.startDate,
        data.endDate || null,
        data.notes || null,
      ]
    );

    await client.query('COMMIT');
    serviceLogger.info('Recurring appointment created', { id: result.rows[0].id });
    return result.rows[0];
  } catch (error) {
    await client.query('ROLLBACK');
    serviceLogger.error('Failed to create recurring appointment', error);
    throw error;
  } finally {
    client.release();
  }
}

/**
 * Get recurring appointments for a customer
 */
export async function getRecurringAppointments(
  customerId: number,
  shopId: number
): Promise<RecurringAppointment[]> {
  try {
    const result = await query(
      `SELECT * FROM recurring_appointments
       WHERE customer_id = $1 AND shop_id = $2
       ORDER BY created_at DESC`,
      [customerId, shopId]
    );
    return result.rows;
  } catch (error) {
    serviceLogger.error('Failed to fetch recurring appointments', error);
    throw error;
  }
}

/**
 * Get all active recurring appointments for a barber
 */
export async function getActiveRecurringForBarber(
  barberId: number,
  shopId: number
): Promise<RecurringAppointment[]> {
  try {
    const result = await query(
      `SELECT * FROM recurring_appointments
       WHERE barber_id = $1 AND shop_id = $2 AND is_active = true
       ORDER BY customer_id`,
      [barberId, shopId]
    );
    return result.rows;
  } catch (error) {
    serviceLogger.error('Failed to fetch recurring appointments for barber', error);
    throw error;
  }
}

/**
 * Update a recurring appointment
 */
export async function updateRecurringAppointment(
  id: number,
  shopId: number,
  updates: {
    barberId?: number;
    timeOfDay?: string;
    endDate?: string;
    isActive?: boolean;
    notes?: string;
  }
): Promise<RecurringAppointment | null> {
  const fields = [];
  const values = [];
  let paramCount = 1;

  if (updates.barberId !== undefined) {
    fields.push(`barber_id = $${paramCount++}`);
    values.push(updates.barberId);
  }
  if (updates.timeOfDay !== undefined) {
    fields.push(`time_of_day = $${paramCount++}`);
    values.push(updates.timeOfDay);
  }
  if (updates.endDate !== undefined) {
    fields.push(`end_date = $${paramCount++}`);
    values.push(updates.endDate);
  }
  if (updates.isActive !== undefined) {
    fields.push(`is_active = $${paramCount++}`);
    values.push(updates.isActive);
  }
  if (updates.notes !== undefined) {
    fields.push(`notes = $${paramCount++}`);
    values.push(updates.notes);
  }

  if (fields.length === 0) {
    return null;
  }

  fields.push(`updated_at = CURRENT_TIMESTAMP`);
  values.push(id, shopId);

  try {
    const result = await query(
      `UPDATE recurring_appointments
       SET ${fields.join(', ')}
       WHERE id = $${paramCount} AND shop_id = $${paramCount + 1}
       RETURNING *`,
      values
    );
    return result.rows[0] || null;
  } catch (error) {
    serviceLogger.error('Failed to update recurring appointment', error);
    throw error;
  }
}

/**
 * Delete (deactivate) a recurring appointment
 */
export async function deleteRecurringAppointment(
  id: number,
  shopId: number
): Promise<boolean> {
  const client = await getClient();

  try {
    await client.query('BEGIN');

    // Soft delete by marking as inactive
    const result = await client.query(
      `UPDATE recurring_appointments
       SET is_active = false, updated_at = CURRENT_TIMESTAMP
       WHERE id = $1 AND shop_id = $2`,
      [id, shopId]
    );

    await client.query('COMMIT');
    serviceLogger.info('Recurring appointment deleted', { id });
    return result.rowCount > 0;
  } catch (error) {
    await client.query('ROLLBACK');
    serviceLogger.error('Failed to delete recurring appointment', error);
    throw error;
  } finally {
    client.release();
  }
}

/**
 * Auto-generate appointments from recurring appointments
 * Should be run by a scheduled job
 */
export async function autoGenerateAppointmentsFromRecurring(
  shopId: number
): Promise<number> {
  const client = await getClient();
  let generatedCount = 0;

  try {
    await client.query('BEGIN');

    // Get all active recurring appointments
    const recurringResult = await client.query(
      `SELECT * FROM recurring_appointments
       WHERE shop_id = $1 AND is_active = true
       AND (end_date IS NULL OR end_date > CURRENT_DATE)
       AND start_date <= CURRENT_DATE`,
      [shopId]
    );

    const now = new Date();
    const nextWeek = new Date(now.getTime() + 7 * 24 * 60 * 60 * 1000);

    for (const recurring of recurringResult.rows) {
      const appointmentDate = calculateNextAppointmentDate(recurring, now);

      // Only generate if within next 7 days
      if (appointmentDate && appointmentDate <= nextWeek) {
        // Check if appointment already exists
        const [hours, minutes] = recurring.time_of_day.split(':');
        const appointmentStart = new Date(appointmentDate);
        appointmentStart.setHours(parseInt(hours), parseInt(minutes), 0);

        const appointmentEnd = new Date(appointmentStart);
        appointmentEnd.setHours(appointmentStart.getHours() + 1);

        const existingAppointment = await client.query(
          `SELECT id FROM appointments
           WHERE recurring_appointment_id = $1
           AND start_time = $2`,
          [recurring.id, appointmentStart.toISOString()]
        );

        if (existingAppointment.rowCount === 0) {
          // Get customer info
          const customerResult = await client.query(
            `SELECT email, name, phone FROM customer_profiles WHERE id = $1`,
            [recurring.customer_id]
          );

          const customer = customerResult.rows[0];
          if (customer) {
            // Create appointment
            const appointmentResult = await client.query(
              `INSERT INTO appointments (
                shop_id, barber_id, customer_id, customer_name, customer_email,
                customer_phone, start_time, end_time, status, notes
              ) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'confirmed', $9)
              RETURNING id`,
              [
                shopId,
                recurring.barber_id,
                recurring.customer_id,
                customer.name,
                customer.email,
                customer.phone,
                appointmentStart.toISOString(),
                appointmentEnd.toISOString(),
                `Auto-generated from recurring: ${recurring.service_name || 'Service'}`,
              ]
            );

            // Track as auto-generated
            if (appointmentResult.rows[0]) {
              await client.query(
                `INSERT INTO auto_generated_appointments (
                  recurring_appointment_id, appointment_id
                ) VALUES ($1, $2)`,
                [recurring.id, appointmentResult.rows[0].id]
              );
              generatedCount++;
            }
          }
        }
      }
    }

    await client.query('COMMIT');
    serviceLogger.info('Auto-generated appointments', { count: generatedCount, shopId });
    return generatedCount;
  } catch (error) {
    await client.query('ROLLBACK');
    serviceLogger.error('Failed to auto-generate appointments', error);
    throw error;
  } finally {
    client.release();
  }
}

/**
 * Helper: Calculate next appointment date based on recurrence
 */
function calculateNextAppointmentDate(
  recurring: RecurringAppointment,
  currentDate: Date
): Date | null {
  const startDate = new Date(recurring.start_date);

  if (currentDate < startDate) {
    return startDate;
  }

  if (recurring.end_date && currentDate > new Date(recurring.end_date)) {
    return null;
  }

  const nextDate = new Date(currentDate);

  if (recurring.recurrence_type === 'weekly') {
    const targetDayOfWeek = recurring.day_of_week;
    const currentDayOfWeek = nextDate.getDay();
    let daysToAdd = targetDayOfWeek - currentDayOfWeek;

    if (daysToAdd <= 0) {
      daysToAdd += 7;
    }

    nextDate.setDate(nextDate.getDate() + daysToAdd);
  } else if (recurring.recurrence_type === 'bi-weekly') {
    const targetDayOfWeek = recurring.day_of_week;
    const currentDayOfWeek = nextDate.getDay();
    let daysToAdd = targetDayOfWeek - currentDayOfWeek;

    if (daysToAdd < 0) {
      daysToAdd += 14;
    } else if (daysToAdd === 0) {
      daysToAdd = 14;
    } else {
      daysToAdd = daysToAdd <= 7 ? daysToAdd : daysToAdd + 7;
    }

    nextDate.setDate(nextDate.getDate() + daysToAdd);
  } else if (recurring.recurrence_type === 'monthly') {
    const targetDayOfMonth = recurring.day_of_month;
    if (nextDate.getDate() > targetDayOfMonth) {
      nextDate.setMonth(nextDate.getMonth() + 1);
    }
    nextDate.setDate(targetDayOfMonth);
  }

  return nextDate;
}

/**
 * Get next appointment date for a recurring appointment
 */
export function getNextAppointmentDate(
  recurring: RecurringAppointment
): Date | null {
  return calculateNextAppointmentDate(recurring, new Date());
}

export default {
  createRecurringAppointment,
  getRecurringAppointments,
  getActiveRecurringForBarber,
  updateRecurringAppointment,
  deleteRecurringAppointment,
  autoGenerateAppointmentsFromRecurring,
  getNextAppointmentDate,
};
